### ISSUE TITLE
[help] how can i use it in my hexo blog?

### ISSUE THREAD

**Issue by 2926295173** [SoraY677/Live2DLib#1]
Hi. I am aoian. a student in china.I like this  live2d model very much. I want to use it in my hexo blog. (https://blog.aoian.cn).
can you help me? 😣

**Comment by SoraY677** [comment]
hi! my name is sora!
nice to me too!
the model that I use is live2d original
so, I create only codes
so, you want to use this model, please visit live2d official site.😭

I’m japanese. so, I’m sorry if misunderstand your question mean

**Comment by 2926295173** [comment]
Oh, it's OK. Thank you, too. my English is not very good.too.I went to the official website to read the documents, but I still unknow how to use live2d in website. Read your code, I understand a lot, including the logic.

**Comment by 2926295173** [comment]
I have run your code in this test. 
https://live2-dl-ib.vercel.app/
it is very good

**Comment by SoraY677** [comment]
OK,OK...I understand!
my code running . I see.

OK... I`ll help you !
so, what do I do?
do you want sample code? or document?
Let me help you!

**Comment by 2926295173** [comment]
ok.thanks.but i do not need.i have known how to use it.

**Comment by 2926295173** [comment]
我又要打扰您了，您能写一下使用文档吗？我发现一个问题。这个卡通人物只能眨眨眼睛，没有其他动作。
我该如何添加一些其他动作，以便该卡通人物可以对鼠标的移动做出反应，比如这个页面[example](https://blog.aoian.cn)。此页面上的小猫可以根据用户电脑鼠标的位置来移动头部。
Excuse me, can you write a document?,I find an issue.This cartoon character can only blink his eyes.No other actions.
How can I add some other actions so that this cartoon character can react to the movement of the mouse, such as this [example:](https://blog.aoian.cn) the kitten on this page can move its head with the movement of the mouse.
またお邪魔したいのですが、使用説明書を書き留めてもらえますか？ 問題が見つかりました。 漫画のキャラクターは目をまばたきするだけで、他の動きはできません。
このページ[例]（https://blog.aoian.cn）のように、漫画のキャラクターがマウスの動きに反応できるように、他のアクションを追加するにはどうすればよいですか。 このページの子猫は、ユーザーのコンピューターのマウスの位置に応じて頭を動かすことができます。

**Comment by SoraY677** [comment]
sorry too late response , aoion.
this program has some functions under this.
- rendering model
- animate character with defined animatetion   
- eye blink
- lip Sync
so, if you want eye move with your mouse, create new functions
I can create it. but I need some time to do.
you wait me????

**Comment by 2926295173** [comment]
ok. thank you very much. I will wait.
